#!/usr/bin/python

import os
import argparse

parser = argparse.ArgumentParser(description='start killswitch')
parser.add_argument('-r', dest='remove', action='store_true')
commandArgs = parser.parse_args()
print commandArgs

if commandArgs.remove:
  os.system("rm /dev/shm/killswitch")
else:
  os.system("touch /dev/shm/killswitch")


